# Generated by Django 5.0.2 on 2024-05-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatemodel',
            name='font',
        ),
        migrations.RemoveField(
            model_name='templatemodel',
            name='font_size',
        ),
        migrations.AddField(
            model_name='templatemodel',
            name='desc',
            field=models.CharField(default='N/A', max_length=40),
        ),
        migrations.AddField(
            model_name='templatemodel',
            name='title',
            field=models.CharField(default='N/A', max_length=30),
        ),
        migrations.AddField(
            model_name='templatemodel',
            name='url',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='templatemodel',
            name='color',
            field=models.CharField(default='N/A', max_length=30),
        ),
    ]
