# Generated by Django 5.0.3 on 2024-05-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0004_templatemodel_font_alter_templatemodel_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatemodel',
            name='font_color',
            field=models.CharField(default='#333', max_length=30),
        ),
        migrations.AlterField(
            model_name='templatemodel',
            name='font',
            field=models.CharField(default='sans-serif', max_length=30),
        ),
    ]
