# Generated by Django 5.0.3 on 2024-05-22 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('plantilla', '0008_alter_templatemodel_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatemodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.magneto_user'),
        ),
    ]
