# Generated by Django 5.0.3 on 2024-05-22 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0011_remove_templatemodel_url_templatemodel_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatemodel',
            name='user',
        ),
    ]
