# Generated by Django 5.0.3 on 2024-05-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0012_remove_templatemodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatemodel',
            name='city',
        ),
        migrations.AddField(
            model_name='templatemodel',
            name='url',
            field=models.URLField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='templatemodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
