# Generated by Django 5.0.3 on 2024-05-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0013_remove_templatemodel_city_templatemodel_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatemodel',
            name='url',
        ),
        migrations.AddField(
            model_name='templatemodel',
            name='city',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='templatemodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
